name: build-test-deploy
on:
    workflow_dispatch:
    push:
        branches: [ "master" ]
        tags:
            - "*"
    pull_request:
        branches: [ "master" ]

jobs:
    build-test-deploy:
        uses: bmc-anvil/bmc-devops/blob/master/.github/workflows/build_test_deploy.yml
        secrets:
            packages_user: ${{secrets.PACKAGES_USER}}
            packages_token: ${{secrets.PACKAGES_TOKEN_RW}}
