name: build-test-deploy
on:
    workflow_dispatch:
    push:
        branches: [ "master" ]
        tags:
            - "*"
    pull_request:
        branches: [ "master" ]

jobs:
    build-test-deploy:
        uses: bmc-anvil/bmc-devops/.github/workflows/build_test_deploy.yml@master
        secrets:
            PACKAGES_USER: ${{secrets.PACKAGES_USER}}
            PACKAGES_TOKEN_RW: ${{secrets.PACKAGES_TOKEN_RW}}
